name: 'CodeCov'

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  coverage:

    runs-on: ubuntu-latest
    name: Create and upload coverage report

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Generate coverage with JaCoCo
        run: mvn -V --color always -ntp clean verify -Ppit '-Dgpg.skip' '-Dfeatures=+GIT(from[HEAD~1]),+gitci'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          files: 'target/site/jacoco/jacoco.xml'
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Aggregate PIT coverage files
        run: mvn -e -B pitest-git:aggregate
      - name: Upload PIT results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pitest
          path: target/pit-reports-ci/
